spring.application.name=dashboard-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/dashboarddb
spring.datasource.username=dashboarduser
spring.datasource.password=dashboardpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=true