spring.application.name=dashboard-api

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5435/dashboarddb
spring.datasource.username=dashboarduser
spring.datasource.password=dashboardpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI / Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-exception=false

# Proxy Configuration
dashboarding.proxy.allowed-schemes=https
dashboarding.proxy.allowed-hosts=calendar.google.com